#
#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#            - POST
#            - OPTIONS
#            - HEAD
#            - PUT
#            - DELETE
#            - PATCH
